### PR TITLE
set meal name color to cyan

### PR DESCRIPTION
**Pull request by Cyanose**
Colored meal names to make difference between meals and entries:
image

### CODE REVIEW

**Comment by ickyicky** [comment]
Instead of creating new `TextStyle` with hardcoded `color: Colors.cyan` it is way better to just copy existing one replacing only color. Additionally, it is not acceptable to hardcode color, use one of colors defined within context's color scheme. There are many examples of how should it be done in applications code, for instance:
```dart
            style: Theme.of(context).textTheme.bodyMedium!.copyWith(
              color: Theme.of(context).colorScheme.secondary,
            ),
```

**Comment by Cyanose** [comment]
Did I get it right this time?

**Comment by ickyicky** [comment]
don't hard code cyan color, use primary or secondary color (it's cyan, but in shade that is consistent with the whole color scheme)

**Comment by Cyanose** [comment]
Okey, yeah now I see, primary is a lot better

**Pull request merged**
